[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang" # used to decrease build time
rustflags = ["-Clink-arg=-fuse-ld=mold"] # switched from lld to mold for faster linking

[alias]
f = "fmt --all -- --config imports_granularity=Crate,group_imports=One"
cl = "clippy --all-targets --all-features"
