[profile.ci-test]
# Use the same settings as release profile
opt-level = 2
# Inherit from release profile
inherits = "release"
# Run tests in parallel
test-threads = "num-cpus"
# Show output for failing tests
failure-output = "immediate"
# Show output for successful tests
success-output = "never"
# Retry failed tests
retries = 0
# Don't cancel test run on first failure
fail-fast = false 